included:
  - Sources
  - Tests

excluded:
  - Sources/XCLogParser/generated
  - Tests/XCLogParserTests/XCTestManifests.swift

disabled_rules:
  - trailing_comma

type_name:
  min_length: 4
  max_length: 60

identifier_name:
  min_length: 3
  max_length: 60
