os: osx
osx_image: xcode10.2
language: swift
branches:
  only:
  - master
cache:
  directories:
  - ".build"
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
- "./ci/ci.sh"
deploy:
  provider: releases
  api_key:
    secure: diGq4+jo0ruvo7UIGOHUj4RBfOJJjAmqU7lAVbh+CbiJEpu6DVZeHBY/Eq1xnlM3ptk1Wqjm1iGVrAYqTIbm5poOJMT0I0/zmdmI0TOX4UbbcQruK0hVfXKe+T+MoJ+5GfeMsAp6JxgPesj0E/CDF98wcuXsdiSkGmd6EyxBtY4cztX9YciGGhROPe3w+Gg7cfqQWk3X/czB7rKAiwKWOgJ4Jfdu2LojrpSwMKryQ4Wu1U+zTjIT/CRNZBpZ+Ye2v6LOs4w0OFyy1z5oarUBwdUmjVrqTrldLth+Q878Oth5gQs5wSB35wQMR/RIAQfkUvmSf6Qd2S8P39s64Wke1ksaJ/stArCOy12Fjm7MynOyn+zccGiPYo2eABA73+QL93e8jNJ3fchXoplzrO1iuKvGfvZVV+mPYp6dUR8XRpU3uhSPDf0KUg/4AZb6kSYXRjbDkhjd+1dwyJoX5D0PLLewVvToXnJAqRg3nAQ8RRcCfdRkrFiYvyrYLot3md/EyM2ksFCD9WZQ+baJMWxd5uId8jSNzXzvFlUUjStqICcauOj64iRfb9IFvhta6JzixF4Y+nXlX4z73rdqCsfWuTuFTelNCJ2tZQ97eRTPSV1S+K9BE7HtSU2COW6xtjwqzAMW6DRXn+pvs+9LlLgmFB7rbrK2rrmAtk/DLGIPdCU=
  file_glob: true
  file: "releases/XCLogParser-*.zip"
  skip_cleanup: true
  draft: true
  on:
    repo: spotify/XCLogParser
    tags: true
